services:
  db:
    image: "postgres:15.3-alpine3.18"
    ports:
      - "9111:5432"
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: sales_dashboard
    volumes:
      - ./data/pg:/var/lib/postgresql/data